version: "3"
services:
  api-database:
    image: mongo:3.2.4
    container_name: "api-database"
    ports:
      - 27017:27017
    command: --smallfiles
    volumes:
      - /data/db .
  api-usuarios:
    build: ./modulo_usuario
    image: api-usuario
    ports:
      - 8084:8084
    links:
      - api-database
  api-eventos:
    build: ./modulo_evento
    image: api-eventos
    ports:
      - 8081:8081
    links:
      - api-database
  web:
    build: ./clienteJSF
    image: web-eventos
    ports:
      - 8080:8080
    links:
      - api-eventos
      - api-usuarios
 
